#!/bin/bash

set -e

install_postgresql_96(){

yum -y install https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm
yum -y install postgresql96-server postgresql96

}


install_postgresql_94(){
    yum -y install \
        https://download.postgresql.org/pub/repos/yum/9.4/redhat/rhel-7-x86_64/pgdg-centos94-9.4-3.noarch.rpm
    yum -y install \
        postgresql94-server postgresql94-contrib postgresql94-devel

    ###########################################
    # Hack alert:
    # For Postgresql 9.4, pg_rewind is not in the main source tree and
    # no packages exist in the repos, so it must be compiled manually
    # and installed on the image until we can move to 9.5
    # See README at
    # https://github.com/vmware/pg_rewind/tree/REL9_4_STABLE
    dev_pkgs="gcc git make readline-devel zlib-devel krb5-devel openssl-devel pam-devel libxml2-devel libxslt-devel python-devel"

    yum install -y $dev_pkgs

    # We need pg_config to be accessible on the path
    mkdir -p /tmp/build
    cd /tmp/build
    git clone https://github.com/vmware/pg_rewind.git --branch REL9_4_STABLE
    git clone https://github.com/postgres/postgres.git --branch REL9_4_STABLE

    ln -s /usr/pgsql-9.4/bin/pg_config /usr/bin/pg_config

    cd pg_rewind
    make USE_PGXS=1 top_srcdir=/tmp/build/postgres install
    ln -sf /usr/pgsql-9.4/bin/pg_rewind /usr/bin/pg_rewind

    # Cleanup

    cd /
    rm -rf /tmp/build
    pip install -c https://git.openstack.org/cgit/openstack/requirements/plain/upper-constraints.txt?h=stable/ocata psycopg2
    yum remove -y $dev_pkgs
}

install_postgresql_94
