#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [[ ${DISTRO_NAME} =~ "centos" ]]; then
    yum install -y qemu-guest-agent
elif [[ ${DISTRO_NAME} =~ "ubuntu" ]]; then
    apt-get install -y qemu-guest-agent
fi
