#!/bin/bash
if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

for kernel_path in /lib/modules/*; do
    kernel_version=${kernel_path##*/}
    dracut -f "/boot/initramfs-$kernel_version.img" "$kernel_version"
done
