#!/bin/bash

yum -y install http://www.percona.com/downloads/percona-release/redhat/0.1-4/percona-release-0.1-4.noarch.rpm
yum -y install Percona-Server-server-56 percona-xtrabackup

sudo mkdir -p /etc/mysql/conf.d/
sudo chown mysql:mysql -R /etc/mysql
