#!/bin/bash

set -xe

cat > /usr/lib/systemd/system/trove-guestagent.service <<EOF
[Unit]
Description=OpenStack Trove Guest
After=syslog.target network.target cloud-init.service

[Service]
Type=simple
ExecStart=/usr/bin/trove-guestagent --config-file /etc/trove/trove-guestagent.conf --config-file /etc/trove/conf.d/guest_info.conf
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable trove-guestagent
